{
 "title": "Couper",
 "tags": [ "couper" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "K8s namespace",
    "query": {
     "query": "label_values(couper_client_request_total, namespace)"
    }
   },
   {
    "name": "job",
    "label": "Scrape Job",
    "query": {
     "query": "label_values(couper_client_request_total, job)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(couper_client_request_total, service_name)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(couper_client_request_total{namespace=\"$namespace\"},service_version)"
    }
   },
   {
    "name": "origin",
    "label": "Backends",
    "query": {
     "query": "label_values(couper_backend_request_total{job=\"$job\", service_name=\"$service\", namespace=\"$namespace\"},origin)"
    }
   },
   {
    "name": "host",
    "label": "Backends",
    "query": {
     "query": "label_values(couper_client_request_total{job=\"$job\", service_name=\"$service\", namespace=\"$namespace\", host!~\"^\\\\d+.*:\\\\d+$\"},host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server: ${host:doublequote}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(couper_client_request_total{job=\"$job\", service_name=\"$service\", namespace=\"$namespace\", host=~\"$host\"} [2m])) by (code) > 0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "95th Percentile of request time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,couper_client_request_duration_seconds{code=\"200\", job=\"$job\", service_name=\"$service\", namespace=\"$namespace\", host=~\"$host\"} [2m]) or histogram_quantile(0.95,sum(rate(couper_client_request_duration_seconds_bucket{code=\"200\", job=\"$job\", service_name=\"$service\", namespace=\"$namespace\", host=~\"$host\"} [2m])) by(le))"
    }
   ]
  },
  {
   "title": "Current client connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(couper_client_connections_count{job=\"$job\", service_name=\"$service\", namespace=\"$namespace\", host=~\"$host\"}) "
    }
   ]
  },
  {
   "title": "Top5 - Errors by type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(increase(couper_client_request_error_types_total{job=\"$job\", service_name=\"$service\", namespace=\"$namespace\", host=~\"$host\"} [2m])) by (error) > 0)",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "5xx requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(couper_client_request_total{job=\"$job\", service_name=\"$service\", code=~\"5.*\", namespace=\"$namespace\", host=~\"$host\"} [$__range])) > 0) * 100 / ignoring(code) group_left sum(increase(couper_client_request_total{job=\"$job\", service_name=\"$service\", code!~\"5.*|0\", namespace=\"$namespace\", host=~\"$host\"} [$__range])) > 0"
    }
   ]
  },
  {
   "title": "Couper version",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "content": "<center>${version}</center>" },
   "targets": [
    {
     "expr": "sum(couper_client_request_total{}) by (service_version)",
     "legendFormat": "{{service_version}}"
    }
   ]
  },
  { "title": "Backend: ${origin:doublequote}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }, "repeat": "origin" },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(couper_backend_request_total{job=\"$job\", service_name=\"$service\", namespace=\"$namespace\", origin=~\"$origin\"} [2m])) by (code) > 0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "95th Percentile of request time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (origin) (quantile_over_time(0.95,couper_backend_request_duration_seconds{code!~\"^5.*|0\", job=\"$job\", service_name=\"$service\", namespace=\"$namespace\",origin=~\"$origin\"} [2m])) or histogram_quantile(0.95,sum(increase(couper_backend_request_duration_seconds_bucket{code!~\"^5.*|0\", job=\"$job\", service_name=\"$service\", namespace=\"$namespace\", origin=~\"$origin\"} [2m])) by (le, hostname))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Current connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(couper_backend_connections_count{job=\"$job\", service_name=\"$service\", namespace=\"$namespace\", origin=~\"$origin\"}) by (origin)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group(last_over_time(couper_backend_up{job=\"$job\", service_name=\"$service\", namespace=\"$namespace\", origin=~\"$origin\"}[1h])) by (origin)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Connections over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(couper_backend_connections_total{job=\"$job\", service_name=\"$service\", namespace=\"$namespace\", origin=~\"$origin\"} [2m])) by (origin)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 33 },
   "targets": [
    {
     "expr": "sum by (backend_name,hostname) (couper_backend_request_total{job=\"$job\", service_name=\"$service\", namespace=\"$namespace\", origin=~\"$origin\"})"
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "panels": [
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(go_goroutines{job=\"$job\", namespace=\"$namespace\"}) / count (go_goroutines{job=\"$job\", namespace=\"$namespace\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(go_memstats_heap_alloc_bytes{job=\"$job\", namespace=\"$namespace\"}) / count (go_memstats_heap_alloc_bytes{job=\"$job\", namespace=\"$namespace\"})",
       "legendFormat": "alloc"
      },
      {
       "expr": "sum(go_memstats_heap_sys_bytes{job=\"$job\", namespace=\"$namespace\"}) / count (go_memstats_heap_alloc_bytes{job=\"$job\", namespace=\"$namespace\"})",
       "legendFormat": "sys"
      },
      {
       "expr": "sum(go_memstats_heap_idle_bytes{job=\"$job\", namespace=\"$namespace\"}) / count (go_memstats_heap_alloc_bytes{job=\"$job\", namespace=\"$namespace\"})",
       "legendFormat": "idle"
      }
     ]
    },
    {
     "title": "CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 13, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(couper_process_cpu_seconds_total{job=\"$job\", namespace=\"$namespace\"} [2m])",
       "legendFormat": "{pod={{pod}}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "go_threads{job=\"$job\", namespace=\"$namespace\"}",
       "legendFormat": "alloc"
      }
     ]
    },
    {
     "title": "Open FDs",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "couper_process_open_fds{job=\"$job\", namespace=\"$namespace\"}",
       "legendFormat": "alloc"
      }
     ]
    }
   ]
  },
  { "title": "Beta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Client request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(couper_client_request_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\", service_name=\"$service\"} [$__rate_interval:10s])) by (le)"
    }
   ]
  },
  {
   "title": "upstream request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(couper_backend_request_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\", service_name=\"$service\"} [$__rate_interval:10s])) by (le)"
    }
   ]
  }
 ]
}