// Code generated by "stringer -type=Error -output=./errors_string.go"; DO NOT EDIT.

package jwt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotConfigured-0]
	_ = x[AlgorithmNotSupported-1]
	_ = x[BearerRequired-2]
	_ = x[ClaimRequired-3]
	_ = x[ClaimValueInvalid-4]
	_ = x[ClaimValueInvalidType-5]
	_ = x[KeyRequired-6]
	_ = x[SignatureInvalid-7]
	_ = x[SourceInvalid-8]
	_ = x[TokenExpired-9]
	_ = x[TokenRequired-10]
	_ = x[Unauthorized-11]
}

const _Error_name = "NotConfiguredAlgorithmNotSupportedBearerRequiredClaimRequiredClaimValueInvalidClaimValueInvalidTypeKeyRequiredSignatureInvalidSourceInvalidTokenExpiredTokenRequiredUnauthorized"

var _Error_index = [...]uint8{0, 13, 34, 48, 61, 78, 99, 110, 126, 139, 151, 164, 176}

func (i Error) String() string {
	if i >= Error(len(_Error_index)-1) {
		return "Error(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Error_name[_Error_index[i]:_Error_index[i+1]]
}
