// Code generated by "stringer -type=HandlerKind -output=./server_string.go"; DO NOT EDIT.

package runtime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[api-0]
	_ = x[endpoint-1]
	_ = x[files-2]
	_ = x[spa-3]
}

const _HandlerKind_name = "apiendpointfilesspa"

var _HandlerKind_index = [...]uint8{0, 3, 11, 16, 19}

func (i HandlerKind) String() string {
	if i >= HandlerKind(len(_HandlerKind_index)-1) {
		return "HandlerKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HandlerKind_name[_HandlerKind_index[i]:_HandlerKind_index[i+1]]
}
