// Code generated by "stringer -type=Error -output=./errors_string.go"; DO NOT EDIT.

package jwt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotConfigured-0]
	_ = x[MissingCredentials-1]
	_ = x[Unauthorized-2]
	_ = x[ParseErrorLineInvalid-3]
	_ = x[ParseErrorLineLengthExceeded-4]
	_ = x[ParseErrorMalformedPassword-5]
	_ = x[ParseErrorMultipleUser-6]
	_ = x[ParseErrorAlgorithmNotSupported-7]
}

const _Error_name = "NotConfiguredMissingCredentialsUnauthorizedParseErrorLineInvalidParseErrorLineLengthExceededParseErrorMalformedPasswordParseErrorMultipleUserParseErrorAlgorithmNotSupported"

var _Error_index = [...]uint8{0, 13, 31, 43, 64, 92, 119, 141, 172}

func (i Error) String() string {
	if i >= Error(len(_Error_index)-1) {
		return "Error(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Error_name[_Error_index[i]:_Error_index[i+1]]
}
